apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: razborges/api-produto:v1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin